"""
themes.py — Manga Notifier theme definitions.
Mirrors the FileTagz theme system: Default Dark, Midnight, Dracula, OLED, Hacker, Rose Pine.
"""

THEMES = {
    "Default Dark": {
        "bg":           "#0F0F0F",
        "card":         "#1C1C1E",
        "card2":        "#2C2C2E",
        "accent":       "#D0BCFF",
        "accent_hover": "#E8DEF8",
        "text":         "#E6E1E5",
        "muted":        "#CAC4D0",
        "link":         "#D0BCFF",
        "success":      "#386A20",
        "warning":      "#D9B42A",
        "error":        "#B3261E",
        "border":       "#49454F",
    },
    "Midnight Blue": {
        "bg":           "#0B0E14",
        "card":         "#11151C",
        "card2":        "#181D27",
        "accent":       "#5E81AC",
        "accent_hover": "#81A1C1",
        "text":         "#D8DEE9",
        "muted":        "#616E88",
        "link":         "#88C0D0",
        "success":      "#A3BE8C",
        "warning":      "#EBCB8B",
        "error":        "#BF616A",
        "border":       "#212836",
    },
    "Dracula": {
        "bg":           "#282A36",
        "card":         "#383A59",
        "card2":        "#44475A",
        "accent":       "#BD93F9",
        "accent_hover": "#D6ACFF",
        "text":         "#F8F8F2",
        "muted":        "#6272A4",
        "link":         "#8BE9FD",
        "success":      "#50FA7B",
        "warning":      "#FFB86C",
        "error":        "#FF5555",
        "border":       "#505367",
    },
    "OLED Black": {
        "bg":           "#000000",
        "card":         "#090909",
        "card2":        "#111111",
        "accent":       "#E2E2E2",
        "accent_hover": "#FFFFFF",
        "text":         "#FFFFFF",
        "muted":        "#666666",
        "link":         "#AAAAAA",
        "success":      "#44CC77",
        "warning":      "#DDAA33",
        "error":        "#CC4444",
        "border":       "#222222",
    },
    "Hacker": {
        "bg":           "#0a0a0a",
        "card":         "#0d110d",
        "card2":        "#111a11",
        "accent":       "#00ff00",
        "accent_hover": "#33ff33",
        "text":         "#00ff00",
        "muted":        "#00aa00",
        "link":         "#00ffcc",
        "success":      "#00ff00",
        "warning":      "#ffff00",
        "error":        "#ff3300",
        "border":       "#003300",
    },
}

THEME_NAMES = list(THEMES.keys())
DEFAULT_THEME = "Default Dark"
