"""
themes.py — Manga Notifier theme definitions.
Mirrors the FileTagz theme system: Default Dark, Midnight, Dracula, OLED, Hacker, Rose Pine.
"""

THEMES = {
    "Default Dark": {
        "bg":           "#0f1117",
        "card":         "#1a1d27",
        "card2":        "#22263a",
        "accent":       "#7c6af7",
        "accent_hover": "#9b8fff",
        "text":         "#e8eaf6",
        "muted":        "#8a8da8",
        "link":         "#7eb8ff",
        "success":      "#4caf84",
        "warning":      "#f5a623",
        "error":        "#e05c5c",
        "border":       "#2c3050",
    },
    "Midnight Blue": {
        "bg":           "#0B0E14",
        "card":         "#11151C",
        "card2":        "#181D27",
        "accent":       "#5E81AC",
        "accent_hover": "#81A1C1",
        "text":         "#D8DEE9",
        "muted":        "#616E88",
        "link":         "#88C0D0",
        "success":      "#A3BE8C",
        "warning":      "#EBCB8B",
        "error":        "#BF616A",
        "border":       "#212836",
    },
    "Dracula": {
        "bg":           "#282A36",
        "card":         "#383A59",
        "card2":        "#44475A",
        "accent":       "#BD93F9",
        "accent_hover": "#D6ACFF",
        "text":         "#F8F8F2",
        "muted":        "#6272A4",
        "link":         "#8BE9FD",
        "success":      "#50FA7B",
        "warning":      "#FFB86C",
        "error":        "#FF5555",
        "border":       "#505367",
    },
    "OLED Black": {
        "bg":           "#000000",
        "card":         "#090909",
        "card2":        "#111111",
        "accent":       "#E2E2E2",
        "accent_hover": "#FFFFFF",
        "text":         "#FFFFFF",
        "muted":        "#666666",
        "link":         "#AAAAAA",
        "success":      "#44CC77",
        "warning":      "#DDAA33",
        "error":        "#CC4444",
        "border":       "#222222",
    },
    "Hacker": {
        "bg":           "#0a0a0a",
        "card":         "#0d110d",
        "card2":        "#111a11",
        "accent":       "#00ff00",
        "accent_hover": "#33ff33",
        "text":         "#00ff00",
        "muted":        "#00aa00",
        "link":         "#00ffcc",
        "success":      "#00ff00",
        "warning":      "#ffff00",
        "error":        "#ff3300",
        "border":       "#003300",
    },
    "Rose Pine": {
        "bg":           "#191724",
        "card":         "#1f1d2e",
        "card2":        "#26233a",
        "accent":       "#ebbcba",
        "accent_hover": "#f6c177",
        "text":         "#e0def4",
        "muted":        "#908caa",
        "link":         "#9ccfd8",
        "success":      "#31748f",
        "warning":      "#f6c177",
        "error":        "#eb6f92",
        "border":       "#312f4b",
    },
}

THEME_NAMES = list(THEMES.keys())
DEFAULT_THEME = "Default Dark"
